<?xml version="1.0" encoding="utf-8"?><Database Name="Ndexpress" Class="deliverylinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=RANGANATH;Initial Catalog=Ndexpress;Integrated Security=True" SettingsObjectName="OriginX.Properties.Settings" SettingsPropertyName="NdexpressConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.insertdelivery" Method="insertdelivery">
    <Parameter Name="delfrom" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="deladd1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="deladd2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="deladd3" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="delcity" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="delmob" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="delto" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="toadd1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="toadd2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="toadd3" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tocity" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tomob" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="deldescript" Type="System.String" DbType="VarChar(150)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addemployees" Method="addemployees">
    <Parameter Name="empname" Type="System.String" DbType="NChar(20)" />
    <Parameter Name="empnic" Type="System.String" DbType="NChar(20)" />
    <Parameter Name="empmob" Type="System.String" DbType="NChar(20)" />
    <Parameter Name="empaddress" Type="System.String" DbType="NChar(20)" />
    <Parameter Name="empbasicsalary" Type="System.String" DbType="NChar(20)" />
    <Parameter Name="empposition" Type="System.String" DbType="NChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.emap" Method="emap">
    <Parameter Name="empname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="empid" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="empdda" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>