#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OriginX
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ndexpress")]
	public partial class deliverylinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public deliverylinqDataContext() : 
				base(global::OriginX.Properties.Settings.Default.NdexpressConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public deliverylinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public deliverylinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public deliverylinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public deliverylinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addemployees")]
		public int addemployees([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string empname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string empnic, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string empmob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string empaddress, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string empbasicsalary, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string empposition)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empname, empnic, empmob, empaddress, empbasicsalary, empposition);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.emap")]
		public int emap([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string empname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string empid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string empdda)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empname, empid, empdda);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertdelivery")]
		public int insertdelivery([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string delfrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string deladd1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string deladd2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string deladd3, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string delcity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string delmob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string delto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string toadd1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string toadd2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string toadd3, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tocity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tomob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] string deldescript)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), delfrom, deladd1, deladd2, deladd3, delcity, delmob, delto, toadd1, toadd2, toadd3, tocity, tomob, deldescript);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
